Formatted prompt with solarized colors and other information
 - Added last command result
 - Added git status
 - Added ssh info

diff --git a/.dotfiles/shell/bash_prompt b/.dotfiles/shell/bash_prompt
--- a/.dotfiles/shell/bash_prompt
+++ b/.dotfiles/shell/bash_prompt
@@ -52,21 +52,21 @@ prompt_git() {
     fi
 }
 
-set_prompts() {
-    local black=""
-    local blue=""
-    local bold=""
-    local cyan=""
-    local green=""
-    local orange=""
-    local purple=""
-    local red=""
-    local reset=""
-    local white=""
-    local yellow=""
+set_colors() {
+    black=""
+    blue=""
+    bold=""
+    cyan=""
+    green=""
+    orange=""
+    purple=""
+    red=""
+    reset=""
+    white=""
+    yellow=""
 
-    local hostStyle=""
-    local userStyle=""
+    hostStyle=""
+    userStyle=""
 
     if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
         tput sgr0 # reset colors
@@ -99,9 +99,23 @@ set_prompts() {
         white="\e[1;37m"
         yellow="\e[1;33m"
     fi
+}
 
-    # build the prompt
+# Default command prompt
+function __prompt_command()
+{
+    set_colors
+    PS1=""
 
+    # capture the exit status of the last command
+    PS1+="\[\033[01;37m\]\$(exit=\$?; if [[ \$exit == 0 ]]; then echo \"\[\033[01;32m\]✓\"; else echo \"\[\033[01;31m\]✗ \$exit\"; fi) "
+ 
+    # if logged in via ssh shows the ip of the client
+    if [ -n "$SSH_CLIENT" ]; then PS1+="\[$yellow\]("${$SSH_CLIENT%% *}")\[$reset\]"; fi
+ 
+    # debian chroot stuff (take it or leave it)
+    PS1+="${debian_chroot:+($debian_chroot)}"
+ 
     # logged in as root
     if [[ "$USER" == "root" ]]; then
         userStyle="\[$bold$red\]"
@@ -117,20 +131,27 @@ set_prompts() {
     fi
 
     # set the terminal title to the current working directory
-    PS1="\[\033]0;\w\007\]"
-
-    PS1+="\n" # newline
-    PS1+="\[$userStyle\]\u" # username
-    PS1+="\[$reset$white\]@"
-    PS1+="\[$hostStyle\]\h" # host
-    PS1+="\[$reset$white\]: "
-    PS1+="\[$green\]\w" # working directory
-    PS1+="\$(prompt_git \"$white on $cyan\")" # git repository details
+    PS1+="\[\033]0;\w\007\]"
+    
+    # set current username
+    #PS1+="\[$userStyle\]\u" 
+    #PS1+="\[$reset$white\]@"
+    
+    # set host
+    #PS1+="\[$hostStyle\]\h" 
+    #PS1+="\[$reset$white\]: "
+    
+    # set working directory
+    PS1+="\[$green\]\w" 
+    
+    # set git repository details
+    PS1+="\$(prompt_git \"$white on $cyan\")"
     PS1+="\n"
-    PS1+="\[$reset$white\]\$ \[$reset\]" # $ (and reset color)
+    
+    # $ (and reset color)
+    PS1+="\[$reset$white\]\$ \[$reset\]" 
 
     export PS1
 }
 
-set_prompts
-unset set_prompts
+PROMPT_COMMAND=__prompt_command
